name: ratrix
description: "Clean Architecture + BLoC + GetIt Flutter starter."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # state / DI
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1

  # networking / session
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.2

  # ui
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_advanced_drawer: ^1.4.0

  # utils
  logger: ^2.6.1
  permission_handler: ^12.0.3
  shadcn_ui: ^0.56.1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  easy_stepper: ^1.2.0
  ph_address_dropdowns: ^0.0.1-beta.2
  flex_color_scheme: ^8.4.0
  lottie: ^3.3.1
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  freezed: ^3.2.6-dev.1
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
